import { expect } from "chai";
import { exists, read, shell, temporaryDir } from "../helpers";
const tmp = temporaryDir();

describe("CLI Export llm-md", () => {
    describe("when generating HTML documentation (default format)", () => {
        const distFolder = tmp.name + "-llms-txt-html";
        let stdoutString = "";

        before(function (done) {
            tmp.create(distFolder);
            const ls = shell("node", [
                "./bin/index-cli.js",
                "-p",
                "./test/fixtures/todomvc-ng2/src/tsconfig.json",
                "-d",
                distFolder,
            ]);
            stdoutString = ls.stdout.toString();
            done();
        });
        after(() => tmp.clean(distFolder));

        it("should create llms.txt alongside index.html", () => {
            expect(exists(`${distFolder}/index.html`)).to.be.true;
            expect(exists(`${distFolder}/llms.txt`)).to.be.true;
        });

        it("llms.txt should start with a markdown heading", () => {
            const file = read(`${distFolder}/llms.txt`, "utf8");
            expect(file).to.match(/^# /);
        });

        it("llms.txt should contain generated-by line", () => {
            const file = read(`${distFolder}/llms.txt`, "utf8");
            expect(file).to.contain("Generated by compodoc");
            expect(file).to.contain("llm-md export");
        });

        it("llms.txt should contain Modules section", () => {
            const file = read(`${distFolder}/llms.txt`, "utf8");
            expect(file).to.contain("## Modules");
        });

        it("llms.txt should contain Components section", () => {
            const file = read(`${distFolder}/llms.txt`, "utf8");
            expect(file).to.contain("## Components");
        });

        it("llms.txt should end with a newline", () => {
            const file = read(`${distFolder}/llms.txt`, "utf8");
            expect(file).to.match(/\n$/);
        });
    });

    describe("when exporting to file with -d flag", () => {
        const distFolder = tmp.name + "-export-llm-md-file";
        let stdoutString = "";

        before(function (done) {
            tmp.create(distFolder);
            const ls = shell("node", [
                "./bin/index-cli.js",
                "-p",
                "./test/fixtures/todomvc-ng2/src/tsconfig.json",
                "-d",
                distFolder,
                "-e",
                "llm-md",
            ]);

            if (ls.stderr.toString() !== "") {
                console.error(`shell error: ${ls.stderr.toString()}`);
            }
            stdoutString = ls.stdout.toString();
            done();
        });
        after(() => tmp.clean(distFolder));

        it("should display generated message", () => {
            expect(stdoutString).to.contain("Documentation generated");
        });

        it("should display llm-md written message", () => {
            expect(stdoutString).to.contain("llm-md export written to");
        });

        it("should create llm-context.md file", () => {
            expect(exists(`${distFolder}/llm-context.md`)).to.be.true;
        });

        it("llm-context.md should have a markdown header with project name", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.match(/^# /);
        });

        it("llm-context.md should contain generated-by line", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("Generated by compodoc");
            expect(file).to.contain("llm-md export");
        });

        it("llm-context.md should have Modules section", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("## Modules");
        });

        it("llm-context.md should have Components section", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("## Components");
        });

        it("llm-context.md should have Services / Injectables section", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("## Services / Injectables");
        });

        it("llm-context.md should render component selectors", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("Selector:");
        });

        it("llm-context.md should render entity names as ### headings", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("### ");
        });

        it("llm-context.md should render file paths", () => {
            const file = read(`${distFolder}/llm-context.md`, "utf8");
            expect(file).to.contain("File: `");
        });

        it("should not create documentation.json", () => {
            expect(exists(`${distFolder}/documentation.json`)).to.be.false;
        });
    });

    describe("when exporting to stdout (no -d flag)", () => {
        let stdoutString = "";
        let stderrString = "";

        before(function (done) {
            const ls = shell("node", [
                "./bin/index-cli.js",
                "-p",
                "./test/fixtures/todomvc-ng2/src/tsconfig.json",
                "-e",
                "llm-md",
            ]);

            stdoutString = ls.stdout.toString();
            stderrString = ls.stderr.toString();
            done();
        });

        it("stdout should start with a markdown heading", () => {
            expect(stdoutString).to.match(/^# /);
        });

        it("stdout should contain generated-by line", () => {
            expect(stdoutString).to.contain("Generated by compodoc");
            expect(stdoutString).to.contain("llm-md export");
        });

        it("stdout should contain Modules section", () => {
            expect(stdoutString).to.contain("## Modules");
        });

        it("stdout should contain Components section", () => {
            expect(stdoutString).to.contain("## Components");
        });

        it("stdout should contain Public functions section or miscellaneous", () => {
            expect(stdoutString).to.match(
                /## Public (functions|type aliases|enumerations|variables)/,
            );
        });

        it("stdout should not contain log noise (Compodoc version banner)", () => {
            expect(stdoutString).to.not.contain("Compodoc v");
        });

        it("stdout should not contain log noise (Documentation generated)", () => {
            expect(stdoutString).to.not.contain("Documentation generated");
        });

        it("stdout should end with a newline", () => {
            expect(stdoutString).to.match(/\n$/);
        });
    });
});
