export class PublicConfiguration {
    public assetsFolder: string;
    public config: string;
    public coverageMinimumPerFile: number;
    public coverageTest: number;
    public coverageTestShowOnlyFailed: boolean;
    public coverageTestThresholdFail: boolean;
    public customFavicon: string;
    public customLogo: string;
    public disableCoverage: boolean;
    public disableDependencies: boolean;
    public disableDomTree: boolean;
    public disableGraph: boolean;
    public disableInternal: boolean;
    public disableLifeCycleHooks: boolean;
    public disablePrivate: boolean;
    public disableProtected: boolean;
    public disableRoutesGraph: boolean;
    public disableSearch: boolean;
    public disableSourceCode: boolean;
    public disableStyleTab: boolean;
    public disableTemplateTab: boolean;
    public exportFormat: string;
    public extTheme: string;
    public files: string;
    public gaID: string;
    public gaSite: string;
    public hideGenerator: boolean;
    public host: string;
    public includes;
    public includesName: string;
    public language: string;
    public minimal: boolean;
    public name: string;
    public navTabConfig;
    public open: boolean;
    public output: string;
    public port: number;
    public serve: boolean;
    public silent: boolean;
    public templates: string;
    public theme: string;
    public toggleMenuItems;
    public tsconfig: string;
    public unitTestCoverage: string;
    public watch: boolean;
    public maxSearchResults: string;

    constructor() {}
}
