name: CI

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

env:
    SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
    SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
    build-and-test:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [20.x, 22.x, 24.x]
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Unit tests
              run: npm run test

            - name: Unit tests refactoring
              run: npm run test-refactoring

            - name: Merge lcov
              if: ${{ matrix.node-version == '22.x' && matrix.os == 'ubuntu-latest' }}
              run: npm run merge-lcov

            - name: Sonarcloud
              if: ${{ matrix.node-version == '22.x' && matrix.os == 'ubuntu-latest' }}
              uses: SonarSource/sonarqube-scan-action@v6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Angular expo test
              if: ${{ matrix.node-version == '24.x' && matrix.os == 'ubuntu-latest' }}
              run: npm run angularexpo

    e2e:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        continue-on-error: true

        strategy:
            fail-fast: false
            matrix:
                node-version: [22.x]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v5

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-${{ env.cache-name }}-
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Install system dependencies for WebKit
              run: npx playwright install-deps webkit

            - name: E2E tests
              run: npm run test-e2e-playwright
